apiVersion: v1
kind: Service
metadata:
  name: webcore001-service
  labels:
    app: webcore001-service
spec:
  type: NodePort
  selector:
    app: webcore001
  ports:
    - protocol: TCP
      nodePort: 30501
      port: 4501
      targetPort: 4501