apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcore001-deployment
spec:
  selector:
    matchLabels:
      app: webcore001
  replicas: 3
  template:
    metadata:
      labels:
        app: webcore001
    spec:
      containers:
        - name: webcore001
          image: gsw/webcore001:v1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4501
          livenessProbe:
            httpGet:
              path: /health
              port: 4501            
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15












